In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame
from pandas import read_csv
from matplotlib import pyplot
#그래프 그리기
tt= pd.read_csv('C:/Users/student/seaborn-data/titanic.csv')
tt

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [ ]:
merge ( 데이터병합 합치기)
:공통열 인덱스기준 2개 데이터프레임 병합
    기준열 인덱스 = 키
키 설정 양쪽데이터프레임
1열앤열 : df 열 키로 df2 열을 키로
공통열 기준으로
pd.merge() 안쓰면 공통된키 사용 
inner join 디폴트값
how='outer' 전체값으로나타남
how = left 왼쪽 키 기준
how = right 오른키
없는것은 결측값으로 채움
키 값이 여러개 데이터 : 가능한 모든 경우의 수 따짐
    (), () - 콤마로 경우의 수 다 넣기
    두 데이터 열이름 같다고 키가 다 되지않는다
    실제값 따지기
    on 인수 : [데이터](실제값: 금액)
right_on left_on  : 
    다르다고 쓰는게 아님 확실하게 위해서  on = '변수명'
    2   열앤인덱스
    어떤 열 ? 오른쪽 인덱스 키
    어느쪽에 인덱스 right_index= True 로 넣으면 됨
  3 인덱스 앤 인덱스 
둘다 인덱스 right /left index = True값
##
join 인덱스 
join이 잔오류가 많다
오류시 바로 merge를 쓰자
# concat 메소드 단순한 데이터 연결
위아래 행을 연결 axis=0 디폴트 
 aixs=1 옆으로 연결
pd.contcat([df_con1, df_con2])
    
    
    

In [ ]:
피봇테이블과 그룹분석
행.열인덱스 보아도 어느열 인덱스 인지 조회하여 펼처놓은것
pivot(행인덱스 열인덱스 데이터열)

피봇처리과정
pivot_table(data, 행인덱스,열인덱스) #없는값은 결측치
#그룹분석
groupby() 메소드
df.groupby(df2.key[])
titanic.groupby(['','',]) #키값 다수 설정가능
groups.sum() #그룹별합계
#pivot_table() 피봇과 그룹바이 메소드 중간 결과 피봇테이블
margins : 평균.합계 행별로 열별로 margins_name 만들수있다
    aggfunc=mean 디폴트값
    aggfunc=sum 변경가능/count
    aggfunc() 넣어서 함수계산
pivot_table   (데이터,행,열)

In [8]:
#컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아니다. 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다. 이런 시작 숫자를 시드(seed)라고 한다. 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 된다. 따라서 시드값은 한 번만 정해주면 된다. 시드는 보통 현재 시각등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있다. 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있다. 이 책에서는 코드의 결과를 재현하기 위해 항상 시드를 설정한다.

파이썬에서 시드를 설정하는 명령은 seed이다. 인수로는 0과 같거나 큰 정수를 넣어준다.
np.random.seed(0) # 0 또는 정수큰 수

이렇게 시드를 설정한 후 rand 명령으로 5개의 난수를 생성해 보자. 다른 난수 관련 명령어를 실행하지 말고 바로 다음 명령을 실행해야 한다. rand 명령은 0과 1사이의 난수를 발생시키는 명령으로 인수로 받은 숫자 횟수만큼 난수를 발생시킨다.

In [9]:
np.random.rand(5) #  예측할 수 없는 무작위 숫자가 나오는 것을 볼 수 있다.

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [12]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [ ]:
이제 시드를 0으로 재설정하고 다시 난수를 발생시켜 본다.


In [14]:
np.random.seed(0) 

In [15]:
np.random.rand(5) #위와 같음

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [16]:
np.random.rand(10) #위와 같음

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [18]:
# 순서 바꾸기
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.random.shuffle(x)
x

array([7, 8, 3, 6, 1, 5, 0, 4, 9, 2])

이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 샘플링(sampling)이라고 한다. 샘플링에는 choice 명령을 사용한다. choice 명령은 다음과 같은 인수를 가질 수 있다.

numpy.random.choice(a, size=None, replace=True, p=None)

a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
size : 정수. 샘플 숫자
replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
p : 배열. 각 데이터가 선택될 수 있는 확률

In [3]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([0, 2, 1, 3, 4])

In [21]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([1, 4, 2])

In [22]:
np.random.choice(5, 10)  # 반복해서 10개 선택

array([3, 3, 2, 4, 2, 0, 0, 4, 0, 4])

In [23]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([2, 3, 3, 3, 3, 0, 3, 3, 2, 2])

rand: 0부터 1사이의 균일 분포
randn: 가우시안 표준 정규 분포 ( )
randint: 균일 분포의 정수 난수
rand 명령은 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성한다. 숫자 인수는 생성할 난수의 크기이다. 여러개의 인수를 넣으면 해당 크기를 가진 행렬을 생성한다.

In [24]:
np.random.rand(3, 5) #배열 3행 5열 

array([[0.75068614, 0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033],
       [0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232]])

randn 명령은 기댓값이 0이고 표준편차가 1인 가우시안 표준 정규 분포를 따르는 난수를 생성한다. 인수 사용법은 rand 명령과 같다. 

In [25]:
np.random.randn(3, 5)

array([[ 1.0657892 , -0.69993739,  0.14407911,  0.3985421 ,  0.02686925],
       [ 1.05583713, -0.07318342, -0.66572066, -0.04411241, -0.36326702],
       [-0.01234481,  0.04212149,  1.95929589, -0.1984257 ,  0.33053441]])

randint 명령은 다음과 같은 인수를 가진다.

numpy.random.randint(low, high=None, size=None) 

만약 high를 입력하지 않으면 0과 low사이의 숫자를, high를 입력하면 low와 high는 사이의 숫자를 출력한다. size는 난수의 숫자이다.

In [26]:
np.random.randint(10, size=10) # 랜덤 int 0에서 10까지의  사이즈 10이하

array([4, 1, 2, 9, 1, 4, 6, 8, 2, 3])

In [27]:
np.random.randint(10, 20, size=10) # 10- 20 까지의 숫자 

array([10, 10, 16, 10, 16, 13, 13, 18, 18, 18])

In [28]:
np.random.randint(10, 20, size=(3, 5)) #size 행열 

array([[12, 13, 12, 10, 18],
       [18, 13, 18, 12, 18],
       [14, 13, 10, 14, 13]])

In [4]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([1, 0, 2])

In [6]:
np.random.choice(5, 10)  # 반복해서 10개 선택

array([1, 2, 3, 4, 3, 1, 3, 2, 2, 0])

In [7]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([3, 2, 3, 3, 2, 3, 2, 3, 3, 3])

In [29]:
# 타이타닉 승객 데이터를 이용한 분석실시
# qcut 아닌 세개의 나이 그룹만들기
# 피봇 테이블 : 표에 잇는 정보를 보다 눈에 쉽게 요약해서 보여줌


피봇테이블 + 그루핑 필수
그룹핑을 하기 위해서는 pivot_table() 함수에서 필수적으로 다음의 파라미터가 들어가야 한다.

DataFrame명
index = ['그룹핑하고 싶은 칼럼명1','그룹핑하고 싶은 칼럼명2',....]
이제 계정코드와 계정과목 칼럼을 인덱스로 하여 그룹핑을 하기 위해서 다음과 같이 입력한다.

In [39]:
#pd.pivot_table(df, index = ['계정코드','계정과목'])

In [41]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
pd.pivot_table(titanic, index=['sex','survived'])

adult_male        age     alone       fare     parch  \
sex    survived                                                         
female 0           0.000000  25.046875  0.333333  23.024385  1.037037   
       1           0.000000  28.847716  0.424893  51.938573  0.515021   
male   0           0.959402  31.618056  0.741453  21.960993  0.207265   
       1           0.807339  27.276022  0.587156  40.821484  0.357798   

                   pclass     sibsp  
sex    survived                      
female 0         2.851852  1.209877  
       1         1.918455  0.515021  
male   0         2.476496  0.440171  
       1         2.018349  0.385321

상기에서 괄호안에는 기본적으로 DataFrame명, index를 넣어야 한다.
index는 하나일 경우에는 index = '계정코드'와 같이 넣을 수 있으며, 두 개 이상일 경우에는 리스트의 형태로 넣으면 된다.
상기와 같이 DataFrame명, index만을 넣으면 데이터 타입이 숫자인 칼럼에 대해서 디폴트로 평균(averge) 값을 보여준다.

In [42]:
#이제 평균값이 아닌 합계, 개수, 표준편차, 분산 등의 산식을 보여주려면 다음과 같이 하여야 한다.
# aggfunc= average 디폴트값 
pd.pivot_table(titanic, index = ['sex','survived'], aggfunc = 'sum')

adult_male       age  alone        fare  parch  pclass  sibsp
sex    survived                                                               
female 0                0.0   1603.00   27.0   1864.9752     84     231     98
       1                0.0   5683.00   99.0  12101.6876    120     447    120
male   0              449.0  11382.50  347.0  10277.7447     97    1159    206
       1               88.0   2536.67   64.0   4449.5418     39     220     42

aggfunc = 'sum' 
aggfunc = sum
aggfunc = [sum] 
aggfunc = ['sum'] 
aggfunc을 리스트로 설정하는 경우 칼럼명이 상단에 나오고, 그렇지 않은 경우 칼럼명이 상단에 나오지 않는 차이가 있다.

In [43]:
#비교
pd.pivot_table(titanic, index = ['sex','survived'], aggfunc = ['sum'])

sum                                                
                adult_male       age  alone        fare parch pclass sibsp
sex    survived                                                           
female 0               0.0   1603.00   27.0   1864.9752    84    231    98
       1               0.0   5683.00   99.0  12101.6876   120    447   120
male   0             449.0  11382.50  347.0  10277.7447    97   1159   206
       1              88.0   2536.67   64.0   4449.5418    39    220    42

2개 이상의 산식을 넣는 경우에는 다음과 같이 3가지 방법 중 하나를 선택할 수 있다.

aggfunc = ['sum', 'count'...] 와 같이 리스트로 처리하면 된다.
aggfunc = [sum, count...] 와 같이 리스트로 처리하면 된다.
aggfunc = [np.sum,...]와 같이 numpy를 불러와서 처리할 수 있다.

In [47]:
pd.pivot_table(titanic, index = ['sex','survived'],
               aggfunc = ['count','sum'])

count                                                   \
                adult_male  age alive alone class deck embark_town embarked   
sex    survived                                                               
female 0                81   64    81    81    81    6          81       81   
       1               233  197   233   233   233   91         231      231   
male   0               468  360   468   468   468   61         468      468   
       1               109   93   109   109   109   45         109      109   

                                                    sum                   \
                fare parch pclass sibsp  who adult_male       age  alone   
sex    survived                                                            
female 0          81    81     81    81   81        0.0   1603.00   27.0   
       1         233   233    233   233  233        0.0   5683.00   99.0   
male   0         468   468    468   468  468      449.0  11382.50  347.0   
       1         109   109    109   109  109       88.0   2536.67   64.0   

                                                
                       fare parch pclass sibsp  
sex    survived                                 
female 0          1864.9752    84    231    98  
       1         12101.6876   120    447   120  
male   0         10277.7447    97   1159   206  
       1          4449.5418    39    220    42

In [53]:
#만약 특정 칼럼(데이터 타입이 integer 또는 float인 경우의 칼럼)에 대한 산식만 구하고 싶다면 다음과 같이 하면 된다.

pd.pivot_table(titanic, index = ['sex','survived'], values = 'embark_town', aggfunc = 'count')

embark_town
sex    survived             
female 0                  81
       1                 231
male   0                 468
       1                 109

In [ ]:
#여기서 복수의 칼럼에 대해서 산식을 구하고 싶으면 values = ['칼럼명1','칼럼명2',...] 형태로 넣으면 된다.


In [57]:
pd.pivot_table(titanic, index = ['sex','survived'], values = ['embark_town','embarked'], aggfunc ='sum' )

sex     survived             
female  0         embark_town    SouthamptonSouthamptonSouthamptonSouthamptonSo...
                  embarked       SSSSSSSSSCSCSSCSSCSSSSSCSSSQSSSSSCSSSSSSSSSSSS...
male    0         embark_town    SouthamptonSouthamptonQueenstownSouthamptonSou...
                  embarked       SSQSSSSQSCSSCSCSSCSQCSSCCSCSSCSSSSCSSSSSSSSSSS...
        1         embark_town    SouthamptonSouthamptonSouthamptonCherbourgSout...
                  embarked       SSSCSCSSSCSCSSSSSSSCCSSSSSSSSSSSQSSSSCSSSSSSSS...
dtype: object

In [ ]:
#pivot_table을 설명할 때 가장 혼돈스러운 것이 columns와 values의 사용방법이다. 여기서 columns는 어디까지나 선택적으로 적용하는 것이다. 이는 관심을 가지는 values를 추가로 구분하기 위해서 선택하는 옵션이다.
# 디폴트로 오름차순으로 정리되기 때문이다. 이를 변경하는 방법에 대해서는 아래에서 설명하기로 한다.

In [61]:
pd.pivot_table(titanic, index = ['sex'], values = ['age'], columns = 'alive', aggfunc = ['count'])

count     
         age     
alive     no  yes
sex              
female    64  197
male     360   93

In [65]:
#NaN처리 pivot_table에서 NaN을 처리하기 위해서는 fill_value 옵션을 이용한다. 아래에서는 NaN을 0으로 처리한다고 가정한다.
pd.pivot_table(titanic, index = ['sex','sibsp'], values = ['age'], columns = 'alive', aggfunc = ['count'], fill_value = 0)

count     
               age     
alive           no  yes
sex    sibsp           
female 0        29  115
       1        23   67
       2         3    9
       3         4    4
       4         4    2
       5         1    0
       8         0    0
male   0       267   60
       1        63   30
       2        11    2
       3         4    0
       4        11    1
       5         4    0
       8         0    0

In [66]:
pd.pivot_table(titanic, index = ['sex','sibsp'], values = ['age'], columns = 'alive', aggfunc = ['count'], fill_value = 0,margins=True)

count            
               age            
alive           no  yes    All
sex    sibsp                  
female 0        29  115  144.0
       1        23   67   90.0
       2         3    9   12.0
       3         4    4    8.0
       4         4    2    6.0
       5         1    0    1.0
       8         0    0    NaN
male   0       267   60  327.0
       1        63   30   93.0
       2        11    2   13.0
       3         4    0    4.0
       4        11    1   12.0
       5         4    0    4.0
       8         0    0    NaN
All            424  290  714.0

pivot_table을 실행한 후에 인덱스에 대하여 필터링을 하고 싶은 경우에는 다음과 같이 인덱스 헤더와 인덱스 값을 조건식으로 설정한다.

pivot_table명.query("계정과목 == ['제품매출', '상품매출']")

query()함수는 전체를 쌍따옴표로 묶고, 필터링 하고 싶은 인덱스 값을 리스트 처리한다.

In [70]:
df1 = pd.pivot_table(titanic, index = ['sex','parch'], values = ['age'], columns = 'alive', aggfunc = ['count'], fill_value = 0,margins=True)
>>> df1.query("parch == ['1','2']")

Empty DataFrame
Columns: [(count, age, no), (count, age, yes), (count, age, All)]
Index: []

In [76]:
 df1 = pd.pivot_table(titanic, index =  ['sex','parch'], 
                    values = ['alive','age' ],
                    aggfunc = ['sum','count' ], 
                    fill_value = 0)
df1

sum count      
                   age   age alive
sex    parch                      
female 0       4707.50   153   194
       1       1397.50    55    60
       2        757.00    42    49
       3        150.00     4     4
       4         74.00     2     2
       5        157.00     4     4
       6         43.00     1     1
male   0      12057.50   368   484
       1       1288.92    55    58
       2        413.75    26    31
       3         16.00     1     1
       4        104.00     2     2
       5         39.00     1     1

In [78]:
#상기 결과를 보면 values 순서가  오름차순으로 대변금액이 먼저 나오는 것을 확인할 수 있다. 차변금액이 먼저 나오고 대변금액이 나중에 나오게 순서를 변경하기 위해서는 먼저 다음과 같이 칼럼 인덱스의 구조를 파악한다.
df1.columns


MultiIndex([(  'sum',   'age'),
            ('count',   'age'),
            ('count', 'alive')],
           )

In [84]:
 df1.reindex_axis(['alive','age'], level = 0, axis = 1)

AttributeError: 'DataFrame' object has no attribute 'reindex_axis'

In [ ]:
bins = [1,20,60, 100] # bin: 